name: CI-Style

on: [push, pull_request]

jobs:
  style-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
    
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install flake8
        run: pip install flake8
    
      - name: Lint
        run: flake8 --max-line-length=88 --exclude migrations